// <auto-generated />
using System;
using GameStoreDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStoreDB.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20230123093244_AddRelations")]
    partial class AddRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameStoreDB.Models.Hersteller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpielId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpielId");

                    b.ToTable("Hersteller");
                });

            modelBuilder.Entity("GameStoreDB.Models.Lagerbestand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SpielId")
                        .HasColumnType("int");

                    b.Property<bool>("Zustand")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SpielId");

                    b.ToTable("Lagerbestaende");
                });

            modelBuilder.Entity("GameStoreDB.Models.Spiel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxSpieler")
                        .HasColumnType("int");

                    b.Property<int>("MinSpieler")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spiele");
                });

            modelBuilder.Entity("GameStoreDB.Models.Spieltyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpielId")
                        .HasColumnType("int");

                    b.Property<int>("Typ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpielId");

                    b.ToTable("Spieltypen");
                });

            modelBuilder.Entity("GameStoreDB.Models.Hersteller", b =>
                {
                    b.HasOne("GameStoreDB.Models.Spiel", null)
                        .WithMany("hersteller")
                        .HasForeignKey("SpielId");
                });

            modelBuilder.Entity("GameStoreDB.Models.Lagerbestand", b =>
                {
                    b.HasOne("GameStoreDB.Models.Spiel", "Spiel")
                        .WithMany("Lagerbestand")
                        .HasForeignKey("SpielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spiel");
                });

            modelBuilder.Entity("GameStoreDB.Models.Spieltyp", b =>
                {
                    b.HasOne("GameStoreDB.Models.Spiel", "Spiel")
                        .WithMany("Typ")
                        .HasForeignKey("SpielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spiel");
                });

            modelBuilder.Entity("GameStoreDB.Models.Spiel", b =>
                {
                    b.Navigation("Lagerbestand");

                    b.Navigation("Typ");

                    b.Navigation("hersteller");
                });
#pragma warning restore 612, 618
        }
    }
}
